services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: openpg
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U odoo -d openpg" ]   # <- checa contra openpg
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:18.0
    depends_on:
      db:
        condition: service_healthy
    command: [
      "odoo",
      "-c", "/etc/odoo/odoo.conf",
      "--db-filter=^openpg$",
      "-d", "openpg",
      "--dev=reload,qweb,xml"
    ]
    ports:
      - "8069:8069"
    environment:
      PGHOST: db
      PGUSER: odoo
      PGPASSWORD: odoo
      ODOO_RC: /etc/odoo/odoo.conf
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
      - ./config:/etc/odoo

volumes:
  odoo-db-data:
  odoo-web-data:
