from . import creacion_avances
from . import tipo_contacto_many2one
from . import dashboard_sale_order
from . import asignar_avances_project_wizard
from . import inherit_project_update
from . import inherit_project_task
from . import inherit_project_project
from . import inherit_sale_order_line
from . import inherit_sale_order
from . import inherit_project_tags
from . import inherit_res_partner
from . import inherit_hr_employee_base
from . import control_planta
from . import control_centro_trabajo
from . import inherit_product_template
from . import renombrar_sale_order_wizard